### ISSUE TITLE
As a Founder, I want multiple options to sign-in to the portal so that I don't have to rely on LinkedIn

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#40]
DESCRIPTION:
Founders reported on several occasions having issues signing-in to the portal because they're LinkedIn email isn't the primary email they use. Also, we're at the mercy of LinkedIn, who also has issues with their authorizations every so often.

We should move to a one-time LinkedIn authorization where they create they're own account or just shift to Google as the login then we could also include other authorizations such as their calendar.

WIREFRAMES / IMAGES:
[to be added]

DOCS:
Here's Google's Sign-In documentation:
https://developers.google.com/identity/sign-in/web/devconsole-project

The left sidebar shows additional options, in particular, "Request Additional Permissions" for calendar.

METRICS:
% of users that sign-in with Google

**Comment by schrizsz** [comment]
with login with social accounts the main issue is always that: the account
they already have may not have the emails linked that the social login
actually gives us. For linkedin login we added the linkedin_email (
zach@gmail.com) field to users as extra to email (which is what they want
to be visible like: zach@zachcorporation.com) (facebook, linkedin send the
primary email -this is confusing for the users because often they don't
know which of their email addresses they use as the primary one, we also
have a password login form that is for backup,
https://v3-portal.alchemistaccelerator.com/login_password )(google sends
the only one email)

Of-course as we have more options they can just click on different ones
until (hopefully) one of them works for them.

I understand that for us the social login would give an error when the
email is not found on the system: "Sorry, we could not find an account for "
zach@gmail.com", please try other login methods"

The old portal used linkedin login with matching users firstname, lastname
or linkedinprofile_url so it was more likely to succeed finding the correct
user, but was less secure as the firstname lastname are not quaranteed to
be unique, what do you thinks if we should also broaden our criteria?. We
can add the firstname, lastname as a fallback and when there are 2 matches
we don't do the login but when we have 1 match we'll proceed logging in the
found user?

**Comment by zachpritchard** [comment]
@schrizsz 

I think the key here is that we do some sort of verification (LinkedIn is fine with me) to start, and then once verified, we allow them to use whatever email they want and then create a password. We're inviting people to join at the moment so it's not that difficult to manage. I think the LinkedIn verification could work in the future as well because if that person wants to join or say someone invites a team member. They would still have to provide the LinkedIn email, but then once the person accepts the invitation. They are prompted to create an account choosing whatever email they wish and then creating their own password.

DESIGNS:
Invitation Email
![email-invitation](https://cloud.githubusercontent.com/assets/12280257/9265227/48952ac6-41e5-11e5-8b72-d0a1e6050524.png)

Create account prompt
![modal-create_your_account](https://cloud.githubusercontent.com/assets/12280257/9265228/4de89a6c-41e5-11e5-8245-54812820c669.png)
Notes: 
Once account is created, they receive an email to verify their email address. This initial sign in will create their account, but we'll have some sort of flag that says their email hasn't been verified.

Verify your email prompt
![modal-verify_your_email](https://cloud.githubusercontent.com/assets/12280257/9265235/5b8633dc-41e5-11e5-8ca2-052c43d5fef8.png)

Let me know if you have any questions. Thanks!

**Comment by schrizsz** [comment]
Actually we have also email verification function built because at first we
had registration with email and password then we moved to linkedin only.

**Comment by zachpritchard** [comment]
I have not heard any issues regarding LinkedIn login so closing!
