### ISSUE TITLE
Alchemist calendar not showing up on V3

### ISSUE THREAD

**Issue by zachpritchard** [AlchemistAcc/portal#44]
DESCRIPTION
The Alchemist calendar isn't showing up on the events calendar. I re-added the URL to the Alchemist Calendar and it still didn't work. 

SCREEN RECORDING
http://g.recordit.co/0kCgkiJaOW.gif

**Comment by VeikoSoomets** [comment]
@schrizsz I looked into it and you are right. For the API to work we just have to enable calendar API from the google developers console. The default API key is empty though (in database settings table) so make sure that you put it manually in the current environment.

@zachpritchard To conclude the text this is a quick fix by Kristian (since he has the correct API key).

**Comment by schrizsz** [comment]
@VeikoSoomets Did you try this with the google drive integrations working? Try this on staging where we have the docs links filled in. It does not work and it is impossible to save settings, I understand that there are different "public API" keys in google for "browser" and for "server" so if we need to have the docs services working we need to have 2 separate settings "browser" and "server" google api key.
@zachpritchard Do we need to have the dashboard links with __previews__ working also on the new portal? You mentioned in a meeting that we will port over some old links and stuff.

**Comment by zachpritchard** [comment]
@schrizsz Yes, we'll still need the links, but I'm not sure if we need the previews anymore depending on the dashboard since we should incorporate the focus. Let's discuss tomorrow morning.
