### ISSUE TITLE
As an Alchemist PM, I want to have a set list of tags for Areas of Expertise and Industry Keywords to facilitate the logic for recommendations

### ISSUE THREAD

**Issue by schrizsz** [AlchemistAcc/portal#7]
Create new setting in global setting where the admin can set a comma separated list of tags that will be recommended.
Make it so that the suggestions come up in the existing tags widget on top of the other tags. Make the tags autoexpand so the user can see the default suggestions.
If the user already has that tag then don't show it (maybe js takes care of this).

**Comment by schrizsz** [comment]
I'll left it with no milestone, so you can decide.

**Comment by zachpritchard** [comment]
In order to be able to give good recommendations, we're going to move to a set group of tags for Areas of Expertise (associated with contacts) and Industry Keyword (associated with companies). With these pre-set lists, founders : companies will no longer be able to create their own and only choose from these options. There's a Google sheet link below with a tab for the list of Areas of Expertise and the list for Industry Keywords.

Also, the Google sheet has a tab that matches up the companies with Industry Keywords and a tab that matches up Contacts with Areas of Expertise. This is a fresh start so these will be each company or contacts tags.

Here's the link to the Google sheet that has all the tabs mentioned above. I will also invite you to the sheet through Google.

https://docs.google.com/a/alchemistaccelerator.com/spreadsheets/d/1957r0W8P3FhtRwF9aNxiDj3JUsuwCaTMlfG17LnH7pM/edit?usp=docslist_api

First step, just clean up the data (lists and matching tags) and restrict access to create new tags. I'll provide wireframes for the founders view when selecting tags by Monday. Let me know if you have any questions.

**Comment by zachpritchard** [comment]
@schrizsz We have new founders coming onboard this week and want them to be choosing from these defined lists for Industry Keywords and Areas of Expertise. I'd like to have it ready by this sprint meaning by tomorrow's spring planning so please prioritize it and let me know if there's something holding it up on our end. Thanks!

**Comment by schrizsz** [comment]
This is in live

**Comment by zachpritchard** [comment]
@schrizsz Thanks for the quick turnaround! I went through and found a few minor errors: 
1. Right now an admin can't edit tags within Manage Tags. Please just fix that functionality because I noticed a misspelling in the tags for Async Framworks, which should be Async Frameworks
2. New addition: Allow an admin to add new Tags. We'll need this in the future anyway so might as well add it now. Specifically, "ME" and "PR" weren't in the tags and need to be added. With this functionality, I can add myself :)

Thanks!

**Comment by schrizsz** [comment]
in live

**Comment by zachpritchard** [comment]
@schrizsz I just did some quick QA and there's still a minor bug. I can add a new tag and then edit the tag name, which is great! The issue is you can only select "Company" in the "Type to show tag on" field. When I edit it or just in general put it as "Founders", receive an error. 

Here's a screenshot of the error:
![screen shot 2015-05-30 at 4 54 29 pm](https://cloud.githubusercontent.com/assets/12280257/7899925/833e5c8e-06ed-11e5-8d7d-3cb905034078.png)

Let me know when it's ready for review. Thanks!

**Comment by schrizsz** [comment]
@zachpritchard Hi I'll fix the error messaging, but the reason is that you already have the tag "ME" for founders.

**Comment by zachpritchard** [comment]
@schrizsz Thanks for clarifying! I actually tried to find it but must have missed it. Can you remove tags?

**Comment by zachpritchard** [comment]
@schrizsz When I search PR and ME to add them as an Area of Expertise, they are not displaying even though they exist in the Manage Tags section. 

Also, please organize the manage tags section in a table format that supports filters and search. Thanks!
